/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import py.com.systvent.bean.dto.DepartamentoDTO;
import py.com.systvent.model.jdbc.DepartamentoDAO;
import py.com.systvent.model.jdbc.DepartamentoDaoJDBC;
import utilitarios.*;
public class VentanaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalView
     */
    data mostrar_datos;
     String set_look ="com.sun.java.swing.plaf.metal.MetalLookAndFeel";
    public VentanaPrincipalView() {
        initComponents();
        mostrar_datos = new data();
        mostrar_datos.el_dato();//primero ejecutar este método para después ejecutar el resto
        lbl_data.setText("Hoy es "+mostrar_datos.dia_semana+ " "+mostrar_datos.dia+" de "+mostrar_datos.mes+" del año "+mostrar_datos.anho);
        timer1.start();
    }
    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        btn_cliente = new javax.swing.JButton();
        lbl_data = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id_del = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updButton = new javax.swing.JButton();
        id_upd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre_upd = new javax.swing.JTextField();
        insButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nombre_ins = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        menu_registros = new javax.swing.JMenu();
        miten_cliente = new javax.swing.JMenuItem();
        miten_direccion = new javax.swing.JMenuItem();
        miten_telefono = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miten_tipo_pago = new javax.swing.JMenuItem();
        miten_funcionarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miten_producto = new javax.swing.JMenuItem();
        miten_unidad = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        miten_salir = new javax.swing.JMenuItem();
        menu_movimiento = new javax.swing.JMenu();
        miten_ventas = new javax.swing.JMenuItem();
        miten_presupuesto = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        miten_reporte_ventas = new javax.swing.JMenuItem();
        miten_reporte_productos = new javax.swing.JMenuItem();
        menu_utilitarios = new javax.swing.JMenu();
        miten_lookandfeel_nimbus = new javax.swing.JMenuItem();
        miten_lookandfeel_liquid = new javax.swing.JMenuItem();
        menu_seguridad = new javax.swing.JMenu();
        miten_cambiar_contraseña = new javax.swing.JMenuItem();
        miten_nivel_acceso = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prototipo de sistema de ventas");

        btn_cliente.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\user-32.png")); // NOI18N
        btn_cliente.setText("Cliente");

        lbl_data.setText("Fecha.:");

        lbl_hora.setText("Hora.:");

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        delButton.setText("Delete");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_del, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_hora)
                    .addComponent(lbl_data))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cliente)
                    .addComponent(selectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delButton)
                    .addComponent(jLabel2)
                    .addComponent(id_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\vet.png")); // NOI18N

        updButton.setText("Update");
        updButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        jLabel4.setText("Nombre:");

        insButton.setText("Insert");
        insButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        menu_registros.setMnemonic('R');
        menu_registros.setText("Registros");

        miten_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_cliente.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\clientes.png")); // NOI18N
        miten_cliente.setText("Cliente");
        miten_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_clienteActionPerformed(evt);
            }
        });
        menu_registros.add(miten_cliente);

        miten_direccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_direccion.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\ciudad.png")); // NOI18N
        miten_direccion.setText("Dirección");
        menu_registros.add(miten_direccion);

        miten_telefono.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_telefono.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\barrio.png")); // NOI18N
        miten_telefono.setText("Telefono");
        miten_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_telefonoActionPerformed(evt);
            }
        });
        menu_registros.add(miten_telefono);
        menu_registros.add(jSeparator1);

        miten_tipo_pago.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_tipo_pago.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\icon-money.png")); // NOI18N
        miten_tipo_pago.setText("Tipo de Pago");
        menu_registros.add(miten_tipo_pago);

        miten_funcionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_funcionarios.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\funcionario.png")); // NOI18N
        miten_funcionarios.setText("Funcionarios");
        menu_registros.add(miten_funcionarios);
        menu_registros.add(jSeparator2);
        menu_registros.add(jSeparator3);

        miten_producto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_producto.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\report_key.png")); // NOI18N
        miten_producto.setText("Reservaciones");
        miten_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_productoActionPerformed(evt);
            }
        });
        menu_registros.add(miten_producto);

        miten_unidad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_unidad.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\page_white_compressed.png")); // NOI18N
        miten_unidad.setText("Resultados");
        miten_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_unidadActionPerformed(evt);
            }
        });
        menu_registros.add(miten_unidad);
        menu_registros.add(jSeparator4);

        miten_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_salir.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\salir.png")); // NOI18N
        miten_salir.setText("Salir");
        miten_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miten_salirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miten_salirMousePressed(evt);
            }
        });
        menu_registros.add(miten_salir);

        menu.add(menu_registros);

        menu_movimiento.setMnemonic('M');
        menu_movimiento.setText("Movimiento");

        miten_ventas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_ventas.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\getmoney.png")); // NOI18N
        miten_ventas.setText("Ventas");
        menu_movimiento.add(miten_ventas);

        miten_presupuesto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_presupuesto.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\money.png")); // NOI18N
        miten_presupuesto.setText("Presupuesto");
        menu_movimiento.add(miten_presupuesto);

        menu.add(menu_movimiento);

        menu_reportes.setMnemonic('I');
        menu_reportes.setText("Reportes");

        miten_reporte_ventas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_reporte_ventas.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\relatorio.png")); // NOI18N
        miten_reporte_ventas.setText("Reporte de Ventas");
        menu_reportes.add(miten_reporte_ventas);

        miten_reporte_productos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_reporte_productos.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\camera_add.png")); // NOI18N
        miten_reporte_productos.setText("Reporte de Productos");
        miten_reporte_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_reporte_productosActionPerformed(evt);
            }
        });
        menu_reportes.add(miten_reporte_productos);

        menu.add(menu_reportes);

        menu_utilitarios.setMnemonic('U');
        menu_utilitarios.setText("Utilitarios");

        miten_lookandfeel_nimbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_lookandfeel_nimbus.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\application_double.png")); // NOI18N
        miten_lookandfeel_nimbus.setText("Look and Feel_Nimbus");
        miten_lookandfeel_nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_lookandfeel_nimbusActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_lookandfeel_nimbus);

        miten_lookandfeel_liquid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_lookandfeel_liquid.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\table.png")); // NOI18N
        miten_lookandfeel_liquid.setText("Look and Feel_Liquid");
        miten_lookandfeel_liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_lookandfeel_liquidActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_lookandfeel_liquid);

        menu.add(menu_utilitarios);

        menu_seguridad.setMnemonic('C');
        menu_seguridad.setText("Seguridad");

        miten_cambiar_contraseña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_cambiar_contraseña.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\lock.png")); // NOI18N
        miten_cambiar_contraseña.setText("Cambiar contraseña actual");
        menu_seguridad.add(miten_cambiar_contraseña);

        miten_nivel_acceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_nivel_acceso.setIcon(new javax.swing.ImageIcon("C:\\vetLeibson\\grafico\\key_delete.png")); // NOI18N
        miten_nivel_acceso.setText("Nivel de acceso");
        menu_seguridad.add(miten_nivel_acceso);

        menu.add(menu_seguridad);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_upd, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(nombre_upd))
                        .addGap(35, 35, 35)
                        .addComponent(insButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updButton)
                    .addComponent(id_upd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(insButton)
                    .addComponent(jLabel5)
                    .addComponent(nombre_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombre_upd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBounds(0, 0, 500, 400);
    }// </editor-fold>//GEN-END:initComponents
public void lookandfeel()
 {
 try
 {
 //La variable set look tiene que estar definida arriba como una variable String
 UIManager.setLookAndFeel(set_look);
 SwingUtilities.updateComponentTreeUI(this);
 }
 catch (Exception error)
 {
 JOptionPane.showMessageDialog(null, error);
 }
}

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        mostrar_datos.leer_hora();
        lbl_hora.setText("Hora actual: "+mostrar_datos.hora);
    }//GEN-LAST:event_timer1OnTime

    private void miten_lookandfeel_liquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_lookandfeel_liquidActionPerformed
        // TODO add your handling code here:
        set_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_miten_lookandfeel_liquidActionPerformed

    private void miten_lookandfeel_nimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_lookandfeel_nimbusActionPerformed
        // TODO add your handling code here:
        set_look = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_miten_lookandfeel_nimbusActionPerformed

    private void miten_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miten_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miten_salirMouseClicked

    private void miten_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_telefonoActionPerformed

    private void miten_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_clienteActionPerformed

    private void miten_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_productoActionPerformed

    private void miten_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_unidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_unidadActionPerformed

    private void miten_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miten_salirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miten_salirMousePressed

    private void miten_reporte_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_reporte_productosActionPerformed
        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/systvent?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Usuario\\Desktop\\Tareas\\7mo semestre\\IS2\\LABS\\lab2\\vetLeibson\\src\\py\\com\\systvent\\reportes\\Productos.jrxml"); //CAMBIAR DEPENDIENDO DE DONDE SE ENCUENTRE EL ARCHIVO .jrxml
            String query = "SELECT * FROM producto";
            
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            
            jdesign.setQuery(updateQuery);
            
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
            
            JasperViewer.viewReport(jprint);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(VentanaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_miten_reporte_productosActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        DepartamentoDAO departamentoDaoS = new DepartamentoDaoJDBC();
        try{
             List<DepartamentoDTO> departamentos = departamentoDaoS.select();
             for (DepartamentoDTO departamentoDTO : departamentos) {
            System.out.print( departamentoDTO );
            System.out.println();
            }
            } catch (SQLException e) {
            System.out.println("Excepcion en la capa de prueba");
            e.printStackTrace();
            }
        
    }//GEN-LAST:event_selectButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        DepartamentoDAO departamentoDaoS = new DepartamentoDaoJDBC();
        int id_delete;
        id_delete=Integer.parseInt(id_del.getText());
        try{
             departamentoDaoS.delete( new DepartamentoDTO(id_delete));
            } catch (SQLException e) {
            System.out.println("Excepcion en la capa de prueba");
            e.printStackTrace();
            }
    }//GEN-LAST:event_delButtonActionPerformed

    private void updButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updButtonActionPerformed
        // TODO add your handling code here:
        DepartamentoDAO departamentoDaoS = new DepartamentoDaoJDBC();
        DepartamentoDTO departamento = new DepartamentoDTO();
        int id_update=Integer.parseInt(id_upd.getText());
        String nombre_update=nombre_upd.getText();
        try{
            DepartamentoDTO departamentoTmp= new DepartamentoDTO();
            departamentoTmp.setCod_departamento(id_update);
            departamentoTmp.setNombre_departamento(nombre_update);
            departamentoDaoS.update(departamentoTmp);
            } catch (SQLException e) {
            System.out.println("Excepcion en la capa de prueba");
            e.printStackTrace();
            }
    }//GEN-LAST:event_updButtonActionPerformed

    private void insButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insButtonActionPerformed
        // TODO add your handling code here:
         DepartamentoDAO departamentoDaoS = new DepartamentoDaoJDBC();
          DepartamentoDTO departamento = new DepartamentoDTO();
        String nombre_insert;
        nombre_insert=nombre_ins.getText();
        departamento.setNombre_departamento(nombre_insert);;
        try{
              departamentoDaoS.insert(departamento);
            } catch (SQLException e) {
            System.out.println("Excepcion en la capa de prueba");
            e.printStackTrace();
            }
    }//GEN-LAST:event_insButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            DepartamentoDAO departamentoDao = new DepartamentoDaoJDBC();

 DepartamentoDTO departamento = new DepartamentoDTO();

 departamento.setNombre_departamento("Producción");;


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton delButton;
    private javax.swing.JTextField id_del;
    private javax.swing.JTextField id_upd;
    private javax.swing.JButton insButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_movimiento;
    private javax.swing.JMenu menu_registros;
    private javax.swing.JMenu menu_reportes;
    private javax.swing.JMenu menu_seguridad;
    private javax.swing.JMenu menu_utilitarios;
    private javax.swing.JMenuItem miten_cambiar_contraseña;
    private javax.swing.JMenuItem miten_cliente;
    private javax.swing.JMenuItem miten_direccion;
    private javax.swing.JMenuItem miten_funcionarios;
    private javax.swing.JMenuItem miten_lookandfeel_liquid;
    private javax.swing.JMenuItem miten_lookandfeel_nimbus;
    private javax.swing.JMenuItem miten_nivel_acceso;
    private javax.swing.JMenuItem miten_presupuesto;
    private javax.swing.JMenuItem miten_producto;
    private javax.swing.JMenuItem miten_reporte_productos;
    private javax.swing.JMenuItem miten_reporte_ventas;
    private javax.swing.JMenuItem miten_salir;
    private javax.swing.JMenuItem miten_telefono;
    private javax.swing.JMenuItem miten_tipo_pago;
    private javax.swing.JMenuItem miten_unidad;
    private javax.swing.JMenuItem miten_ventas;
    private javax.swing.JTextField nombre_ins;
    private javax.swing.JTextField nombre_upd;
    private javax.swing.JButton selectButton;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private javax.swing.JButton updButton;
    // End of variables declaration//GEN-END:variables
}
